services:

  database:
    image: mysql:8.0
    container_name: task_manager_mysql
    restart: always

    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: tmp
      MYSQL_PASSWORD: tmp
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - database_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: task_manager_phpmyadmin
    restart: always

    environment:
      PMA_HOST: database
      PMA_PORT: 3306

    depends_on:
      - database

    ports:
      - "8080:80"


volumes:
  database_data: